/** Declaration file generated by dts-gen */

export function fieldDelimiter(delimiter: any): any;

export function formatValueByType(): any;

export function generateJsonFileFromCsv(inputFileName: any, outputFileName: any): void;

export function getJsonFromCsv(inputFileName: any): any;

export function jsonToCsv(inputFileName: any, outputFileName: any): void;

export namespace fieldDelimiter {
    const prototype: {
    };

}

export namespace formatValueByType {
    const prototype: {
    };

}

export namespace generateJsonFileFromCsv {
    const prototype: {
    };

}

export namespace getJsonFromCsv {
    const prototype: {
    };

}

export namespace jsonToCsv {
    const prototype: {
    };

}

